/** Lista de demonstração para QA testar import/sync sem extensão Crunchyroll. */
export const QA_DEMO_WATCHLIST_ITEMS: Record<string, unknown>[] = [
  {
    crunchyrollId: 'qa-demo-one-piece',
    title: 'ONE PIECE',
    posterUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx21.jpg',
    crunchyrollUrl: 'https://www.crunchyroll.com/series/one-piece',
    season: 1,
    episode: 1100,
    totalEpisodes: 0,
    hasDub: true,
    status: 'continuar',
    lists: ['Watching'],
    note: 'Importado via mock QA',
  },
  {
    crunchyrollId: 'qa-demo-demon-slayer',
    title: 'Demon Slayer: Kimetsu no Yaiba',
    posterUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx101922.jpg',
    crunchyrollUrl: 'https://www.crunchyroll.com/series/demon-slayer',
    season: 4,
    episode: 8,
    totalEpisodes: 8,
    hasDub: true,
    status: 'comecar',
    lists: ['Plan to Watch'],
    note: 'Importado via mock QA',
  },
  {
    crunchyrollId: 'qa-demo-jujutsu',
    title: 'Jujutsu Kaisen',
    posterUrl: 'https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx113415.jpg',
    crunchyrollUrl: 'https://www.crunchyroll.com/series/jujutsu-kaisen',
    season: 2,
    episode: 23,
    totalEpisodes: 23,
    hasDub: false,
    status: 'terminado',
    lists: ['Completed'],
    note: 'Importado via mock QA',
  },
];
